# @package _group_._name_

_target_: datasets.breakfast_50salads.Breakfast50Salads
which: Breakfast
root: ${dataset.breakfast.common.data_dir}
splits_dir: ${dataset.breakfast.common.splits_dir}
classes_fpath: ${dataset.breakfast.common.classes_fpath}
is_train: true
fold: ${dataset.breakfast.common.fold}
sample_strategy: last_clip
annot_reader_fn: ${dataset.breakfast.annot_reader_fn}
conv_to_anticipate_fn:
  _target_: datasets.base_video_dataset.convert_to_dense_anticipation
process_df_before_read_fn:
  _target_: datasets.base_video_dataset.process_df_for_dense_anticpation
  obs_ratio: [0.2, 0.7]  # Randomly pick at training time
  pred_steps: 20
  fixed_duration: null
  fixed_duration_obs: ${.fixed_duration}
