# @package _group_

_target_: models.video_classification.mmaction_model
type: "Recognizer3D"
backbone:
  type: "ResNet3dSlowOnly"
  depth: 50
  pretrained: null
  lateral: false
  conv1_kernel: [1, 7, 7]
  conv1_stride_t: 1
  pool1_stride_t: 1
  inflate: [0, 0, 1, 1]
  norm_eval: false
cls_head:  # Will be dropped later, so parameters don't really matter
  type: "I3DHead"
  in_channels: 2048
  num_classes: 400  # Will be dropped anyway, doesn't matter what this is
  spatial_type: "avg"
  dropout_ratio: 0.5
