# @package _group_._name_

_target_: datasets.epic_kitchens.EPICKitchens
version: ${dataset.epic_kitchens.common.version}

root:
  - ${dataset.epic_kitchens.common.data_dir}/train
  - ${dataset.epic_kitchens.common.data_dir}/test
annotation_path:
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_train_action_labels.pkl
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_test_s1_timestamps.pkl
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_test_s2_timestamps.pkl
annotation_dir: ${dataset.epic_kitchens.common.annot_dir}
label_type: ${dataset.epic_kitchens.common.label_type}
sample_strategy: last_clip
