# @package _group_._name_

_target_: datasets.epic_kitchens.EPICKitchens
root: ${dataset.epic_kitchens.common.data_dir}/train
annotation_path:
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_train_action_labels.pkl
annotation_dir: ${dataset.epic_kitchens.common.annot_dir}
label_type: ${dataset.epic_kitchens.common.label_type}
sample_strategy: "center_clip"
# https://github.com/fpv-iplab/rulstm/blob/master/RULSTM/data/validation_videos.csv
only_keep_videos: ${dataset.epic_kitchens.common.rulstm_annot_dir}/validation_videos.csv
action_labels_fpath: ${dataset.epic_kitchens.common.rulstm_annot_dir}/actions.csv
conv_to_anticipate_fn:
  _target_: datasets.base_video_dataset.convert_to_anticipation
  tau_a: ${dataset.epic_kitchens.common.tau_a}
  tau_o: ${dataset.epic_kitchens.common.tau_o}
