# @package _group_._name_

_target_: datasets.epic_kitchens.EPICKitchens
root: ${dataset.epic_kitchens.common.data_dir}/test
annotation_path:
  - ${dataset.epic_kitchens.common.annot_dir}/EPIC_test_s2_timestamps.pkl
annotation_dir: ${dataset.epic_kitchens.common.annot_dir}
label_type: ${dataset.epic_kitchens.common.label_type}
sample_strategy: "center_clip"
action_labels_fpath: ${dataset.epic_kitchens.common.rulstm_annot_dir}/actions.csv
conv_to_anticipate_fn:
  _target_: datasets.base_video_dataset.convert_to_anticipation
  tau_a: ${dataset.epic_kitchens.common.tau_a}
  tau_o: ${dataset.epic_kitchens.common.tau_o}
