# @package _group_._name_

_target_: datasets.oops.Oops
root: ${dataset.oops.common.vid_dir}/train
splits_file: ${dataset.oops.common.annot_dir}/train_filtered.txt
transition_times_json: ${dataset.oops.common.annot_dir}/transition_times.json
keep_unlabeled: true
sample_strategy: random_clip
